package com.stomeo.finalguessed;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class ArrayListPalabras {

    private static List<ListaPalabras> listaCapitales() {

        final List<ListaPalabras> listaCapitales = new ArrayList<>();

        if (Locale.getDefault().getISO3Language().equals("eng")) {
            final ListaPalabras capital1 = new ListaPalabras("KABUL", 1);
            final ListaPalabras capital2 = new ListaPalabras("TIRANA", 2);
            final ListaPalabras capital3 = new ListaPalabras("LUANDA", 3);
            final ListaPalabras capital4 = new ListaPalabras("RIAD", 4);
            final ListaPalabras capital5 = new ListaPalabras("VIENNA", 5);
            final ListaPalabras capital6 = new ListaPalabras("BRUSSLS", 6);
            final ListaPalabras capital7 = new ListaPalabras("SUCRE", 7);
            final ListaPalabras capital8 = new ListaPalabras("OTTAWA", 8);
            final ListaPalabras capital9 = new ListaPalabras("ZAGREB", 9);
            final ListaPalabras capital10 = new ListaPalabras("SANTIAGO", 10);
            final ListaPalabras capital11 = new ListaPalabras("COPENHAGUE", 11);
            final ListaPalabras capital12 = new ListaPalabras("ROSEAU", 12);
            final ListaPalabras capital13 = new ListaPalabras("QUITO", 13);
            final ListaPalabras capital14 = new ListaPalabras("MADRID", 14);
            final ListaPalabras capital15 = new ListaPalabras("TALLIN", 15);
            final ListaPalabras capital16 = new ListaPalabras("ATHENS", 16);
            final ListaPalabras capital17 = new ListaPalabras("GUATEMALA", 17);
            final ListaPalabras capital18 = new ListaPalabras("MALABO", 18);
            final ListaPalabras capital19 = new ListaPalabras("BUDAPEST", 19);
            final ListaPalabras capital20 = new ListaPalabras("BAGDAD", 20);
            final ListaPalabras capital21 = new ListaPalabras("ROME", 21);
            final ListaPalabras capital22 = new ListaPalabras("TOKYO", 22);
            final ListaPalabras capital23 = new ListaPalabras("LUXEMBURG", 23);
            final ListaPalabras capital24 = new ListaPalabras("BISKEK", 24);
            final ListaPalabras capital25 = new ListaPalabras("RABAT", 25);
            final ListaPalabras capital26 = new ListaPalabras("OSLO", 26);
            final ListaPalabras capital27 = new ListaPalabras("ABUYA", 27);
            final ListaPalabras capital28 = new ListaPalabras("WELLINGTON", 28);
            final ListaPalabras capital29 = new ListaPalabras("LIMA", 29);
            final ListaPalabras capital30 = new ListaPalabras("LISBOA", 30);

            listaCapitales.add(capital1);
            listaCapitales.add(capital2);
            listaCapitales.add(capital3);
            listaCapitales.add(capital4);
            listaCapitales.add(capital5);
            listaCapitales.add(capital6);
            listaCapitales.add(capital7);
            listaCapitales.add(capital8);
            listaCapitales.add(capital9);
            listaCapitales.add(capital10);
            listaCapitales.add(capital11);
            listaCapitales.add(capital12);
            listaCapitales.add(capital13);
            listaCapitales.add(capital14);
            listaCapitales.add(capital15);
            listaCapitales.add(capital16);
            listaCapitales.add(capital17);
            listaCapitales.add(capital18);
            listaCapitales.add(capital19);
            listaCapitales.add(capital20);
            listaCapitales.add(capital21);
            listaCapitales.add(capital22);
            listaCapitales.add(capital23);
            listaCapitales.add(capital24);
            listaCapitales.add(capital25);
            listaCapitales.add(capital26);
            listaCapitales.add(capital27);
            listaCapitales.add(capital28);
            listaCapitales.add(capital29);
            listaCapitales.add(capital30);
        } else {
            final ListaPalabras capital1 = new ListaPalabras("KABUL", 1);
            final ListaPalabras capital2 = new ListaPalabras("TIRANA", 2);
            final ListaPalabras capital3 = new ListaPalabras("LUANDA", 3);
            final ListaPalabras capital4 = new ListaPalabras("RIAD", 4);
            final ListaPalabras capital5 = new ListaPalabras("VIENA", 5);
            final ListaPalabras capital6 = new ListaPalabras("BRUSELAS", 6);
            final ListaPalabras capital7 = new ListaPalabras("SUCRE", 7);
            final ListaPalabras capital8 = new ListaPalabras("OTTAWA", 8);
            final ListaPalabras capital9 = new ListaPalabras("ZAGREB", 9);
            final ListaPalabras capital10 = new ListaPalabras("SANTIAGO", 10);
            final ListaPalabras capital11 = new ListaPalabras("COPENHAGUE", 11);
            final ListaPalabras capital12 = new ListaPalabras("ROSEAU", 12);
            final ListaPalabras capital13 = new ListaPalabras("QUITO", 13);
            final ListaPalabras capital14 = new ListaPalabras("MADRID", 14);
            final ListaPalabras capital15 = new ListaPalabras("TALLIN", 15);
            final ListaPalabras capital16 = new ListaPalabras("ATENAS", 16);
            final ListaPalabras capital17 = new ListaPalabras("GUATEMALA", 17);
            final ListaPalabras capital18 = new ListaPalabras("MALABO", 18);
            final ListaPalabras capital19 = new ListaPalabras("BUDAPEST", 19);
            final ListaPalabras capital20 = new ListaPalabras("BAGDAD", 20);
            final ListaPalabras capital21 = new ListaPalabras("ROMA", 21);
            final ListaPalabras capital22 = new ListaPalabras("TOKIO", 22);
            final ListaPalabras capital23 = new ListaPalabras("LUXEMBURGO", 23);
            final ListaPalabras capital24 = new ListaPalabras("BISKEK", 24);
            final ListaPalabras capital25 = new ListaPalabras("RABAT", 25);
            final ListaPalabras capital26 = new ListaPalabras("OSLO", 26);
            final ListaPalabras capital27 = new ListaPalabras("ABUYA", 27);
            final ListaPalabras capital28 = new ListaPalabras("WELLINGTON", 28);
            final ListaPalabras capital29 = new ListaPalabras("LIMA", 29);
            final ListaPalabras capital30 = new ListaPalabras("LISBOA", 30);

            listaCapitales.add(capital1);
            listaCapitales.add(capital2);
            listaCapitales.add(capital3);
            listaCapitales.add(capital4);
            listaCapitales.add(capital5);
            listaCapitales.add(capital6);
            listaCapitales.add(capital7);
            listaCapitales.add(capital8);
            listaCapitales.add(capital9);
            listaCapitales.add(capital10);
            listaCapitales.add(capital11);
            listaCapitales.add(capital12);
            listaCapitales.add(capital13);
            listaCapitales.add(capital14);
            listaCapitales.add(capital15);
            listaCapitales.add(capital16);
            listaCapitales.add(capital17);
            listaCapitales.add(capital18);
            listaCapitales.add(capital19);
            listaCapitales.add(capital20);
            listaCapitales.add(capital21);
            listaCapitales.add(capital22);
            listaCapitales.add(capital23);
            listaCapitales.add(capital24);
            listaCapitales.add(capital25);
            listaCapitales.add(capital26);
            listaCapitales.add(capital27);
            listaCapitales.add(capital28);
            listaCapitales.add(capital29);
            listaCapitales.add(capital30);
        }
        return listaCapitales;
    }


    private static List<ListaPalabras> listaComidas() {
        final List<ListaPalabras> listaComidas = new ArrayList<>();

        if (Locale.getDefault().getISO3Language().equals("eng")) {
            final ListaPalabras comida1 = new ListaPalabras("PAELLA", 1);
            final ListaPalabras comida2 = new ListaPalabras("PIZZA", 2);
            final ListaPalabras comida3 = new ListaPalabras("FISH", 3);
            final ListaPalabras comida4 = new ListaPalabras("MACARONI", 4);
            final ListaPalabras comida5 = new ListaPalabras("POPCORN", 5);
            final ListaPalabras comida6 = new ListaPalabras("POTATO", 6);
            final ListaPalabras comida7 = new ListaPalabras("BREAD", 7);
            final ListaPalabras comida8 = new ListaPalabras("BEANS", 8);
            final ListaPalabras comida9 = new ListaPalabras("RICE", 9);
            final ListaPalabras comida10 = new ListaPalabras("MEATBALLS", 10);
            final ListaPalabras comida11 = new ListaPalabras("LIME", 11);
            final ListaPalabras comida12 = new ListaPalabras("STRAWBERRY", 12);
            final ListaPalabras comida13 = new ListaPalabras("BANANA", 13);
            final ListaPalabras comida14 = new ListaPalabras("CANNELLONI", 14);
            final ListaPalabras comida15 = new ListaPalabras("COOKED", 15);
            final ListaPalabras comida16 = new ListaPalabras("ORANGE", 16);
            final ListaPalabras comida17 = new ListaPalabras("CHEESE", 17);
            final ListaPalabras comida18 = new ListaPalabras("LENTILS", 18);
            final ListaPalabras comida19 = new ListaPalabras("CHICKEN", 19);
            final ListaPalabras comida20 = new ListaPalabras("PEASE", 20);
            final ListaPalabras comida21 = new ListaPalabras("TOMATO", 21);
            final ListaPalabras comida22 = new ListaPalabras("BEETROOT", 22);
            final ListaPalabras comida23 = new ListaPalabras("CHERRY", 23);
            final ListaPalabras comida24 = new ListaPalabras("FIG", 24);
            final ListaPalabras comida25 = new ListaPalabras("APPLE", 25);
            final ListaPalabras comida26 = new ListaPalabras("PEAR", 26);
            final ListaPalabras comida27 = new ListaPalabras("HAM", 27);
            final ListaPalabras comida28 = new ListaPalabras("NECTARINE", 28);
            final ListaPalabras comida29 = new ListaPalabras("CROQUETTES", 29);
            final ListaPalabras comida30 = new ListaPalabras("TORTILLA", 30);

            listaComidas.add(comida1);
            listaComidas.add(comida2);
            listaComidas.add(comida3);
            listaComidas.add(comida4);
            listaComidas.add(comida5);
            listaComidas.add(comida6);
            listaComidas.add(comida7);
            listaComidas.add(comida8);
            listaComidas.add(comida9);
            listaComidas.add(comida10);
            listaComidas.add(comida11);
            listaComidas.add(comida12);
            listaComidas.add(comida13);
            listaComidas.add(comida14);
            listaComidas.add(comida15);
            listaComidas.add(comida16);
            listaComidas.add(comida17);
            listaComidas.add(comida18);
            listaComidas.add(comida19);
            listaComidas.add(comida20);
            listaComidas.add(comida21);
            listaComidas.add(comida22);
            listaComidas.add(comida23);
            listaComidas.add(comida24);
            listaComidas.add(comida25);
            listaComidas.add(comida26);
            listaComidas.add(comida27);
            listaComidas.add(comida28);
            listaComidas.add(comida29);
            listaComidas.add(comida30);
        } else {
            final ListaPalabras comida1 = new ListaPalabras("PAELLA", 1);
            final ListaPalabras comida2 = new ListaPalabras("PIZZA", 2);
            final ListaPalabras comida3 = new ListaPalabras("PESCADO", 3);
            final ListaPalabras comida4 = new ListaPalabras("MACARRONES", 4);
            final ListaPalabras comida5 = new ListaPalabras("PALOMITAS", 5);
            final ListaPalabras comida6 = new ListaPalabras("PATATA", 6);
            final ListaPalabras comida7 = new ListaPalabras("PAN", 7);
            final ListaPalabras comida8 = new ListaPalabras("JUDIAS", 8);
            final ListaPalabras comida9 = new ListaPalabras("ARROZ", 9);
            final ListaPalabras comida10 = new ListaPalabras("ALBONDIGAS", 10);
            final ListaPalabras comida11 = new ListaPalabras("LIMA", 11);
            final ListaPalabras comida12 = new ListaPalabras("FRESA", 12);
            final ListaPalabras comida13 = new ListaPalabras("PLATANO", 13);
            final ListaPalabras comida14 = new ListaPalabras("CANELONES", 14);
            final ListaPalabras comida15 = new ListaPalabras("COCIDO", 15);
            final ListaPalabras comida16 = new ListaPalabras("NARANJA", 16);
            final ListaPalabras comida17 = new ListaPalabras("QUESO", 17);
            final ListaPalabras comida18 = new ListaPalabras("LENTEJAS", 18);
            final ListaPalabras comida19 = new ListaPalabras("POLLO", 19);
            final ListaPalabras comida20 = new ListaPalabras("GUISANTES", 20);
            final ListaPalabras comida21 = new ListaPalabras("TOMATE", 21);
            final ListaPalabras comida22 = new ListaPalabras("REMOLACHA", 22);
            final ListaPalabras comida23 = new ListaPalabras("CEREZA", 23);
            final ListaPalabras comida24 = new ListaPalabras("HIGO", 24);
            final ListaPalabras comida25 = new ListaPalabras("MANZANA", 25);
            final ListaPalabras comida26 = new ListaPalabras("PERA", 26);
            final ListaPalabras comida27 = new ListaPalabras("JAMON", 27);
            final ListaPalabras comida28 = new ListaPalabras("NECTARINA", 28);
            final ListaPalabras comida29 = new ListaPalabras("CROQUETAS", 29);
            final ListaPalabras comida30 = new ListaPalabras("TORTILLA", 30);

            listaComidas.add(comida1);
            listaComidas.add(comida2);
            listaComidas.add(comida3);
            listaComidas.add(comida4);
            listaComidas.add(comida5);
            listaComidas.add(comida6);
            listaComidas.add(comida7);
            listaComidas.add(comida8);
            listaComidas.add(comida9);
            listaComidas.add(comida10);
            listaComidas.add(comida11);
            listaComidas.add(comida12);
            listaComidas.add(comida13);
            listaComidas.add(comida14);
            listaComidas.add(comida15);
            listaComidas.add(comida16);
            listaComidas.add(comida17);
            listaComidas.add(comida18);
            listaComidas.add(comida19);
            listaComidas.add(comida20);
            listaComidas.add(comida21);
            listaComidas.add(comida22);
            listaComidas.add(comida23);
            listaComidas.add(comida24);
            listaComidas.add(comida25);
            listaComidas.add(comida26);
            listaComidas.add(comida27);
            listaComidas.add(comida28);
            listaComidas.add(comida29);
            listaComidas.add(comida30);
        }

        return listaComidas;
    }

    private static List<ListaPalabras> listaAnimales() {
        final List<ListaPalabras> listaAnimales = new ArrayList<>();

        if (Locale.getDefault().getISO3Language().equals("eng")) {
            final ListaPalabras animal1 = new ListaPalabras("DOG", 1);
            final ListaPalabras animal2 = new ListaPalabras("BEAR", 2);
            final ListaPalabras animal3 = new ListaPalabras("SNAKE", 3);
            final ListaPalabras animal4 = new ListaPalabras("CROCODILE", 4);
            final ListaPalabras animal5 = new ListaPalabras("PANTHER", 5);
            final ListaPalabras animal6 = new ListaPalabras("OWL", 6);
            final ListaPalabras animal7 = new ListaPalabras("BULL", 7);
            final ListaPalabras animal8 = new ListaPalabras("CAT", 8);
            final ListaPalabras animal9 = new ListaPalabras("TIGER", 9);
            final ListaPalabras animal10 = new ListaPalabras("SWAN", 10);
            final ListaPalabras animal11 = new ListaPalabras("DUCK", 11);
            final ListaPalabras animal12 = new ListaPalabras("DEER", 12);
            final ListaPalabras animal13 = new ListaPalabras("DONKEY", 13);
            final ListaPalabras animal14 = new ListaPalabras("SAWHORSE", 14);
            final ListaPalabras animal15 = new ListaPalabras("PIGEON", 15);
            final ListaPalabras animal16 = new ListaPalabras("GIRAFFE", 16);
            final ListaPalabras animal17 = new ListaPalabras("CHEETAH", 17);
            final ListaPalabras animal18 = new ListaPalabras("HIPPO", 18);
            final ListaPalabras animal19 = new ListaPalabras("FROG", 19);
            final ListaPalabras animal20 = new ListaPalabras("ELEPHANT", 20);
            final ListaPalabras animal21 = new ListaPalabras("KANGAROO", 21);
            final ListaPalabras animal22 = new ListaPalabras("HORSE", 22);
            final ListaPalabras animal23 = new ListaPalabras("MONKEY", 23);
            final ListaPalabras animal24 = new ListaPalabras("TURTLE", 24);
            final ListaPalabras animal25 = new ListaPalabras("RABBIT", 25);
            final ListaPalabras animal26 = new ListaPalabras("CAMEL", 26);
            final ListaPalabras animal27 = new ListaPalabras("PARROT", 27);
            final ListaPalabras animal28 = new ListaPalabras("CHAMELEON", 28);
            final ListaPalabras animal29 = new ListaPalabras("FLAMINGO", 29);
            final ListaPalabras animal30 = new ListaPalabras("DOLPHIN", 30);

            listaAnimales.add(animal1);
            listaAnimales.add(animal2);
            listaAnimales.add(animal3);
            listaAnimales.add(animal4);
            listaAnimales.add(animal5);
            listaAnimales.add(animal6);
            listaAnimales.add(animal7);
            listaAnimales.add(animal8);
            listaAnimales.add(animal9);
            listaAnimales.add(animal10);
            listaAnimales.add(animal11);
            listaAnimales.add(animal12);
            listaAnimales.add(animal13);
            listaAnimales.add(animal14);
            listaAnimales.add(animal15);
            listaAnimales.add(animal16);
            listaAnimales.add(animal17);
            listaAnimales.add(animal18);
            listaAnimales.add(animal19);
            listaAnimales.add(animal20);
            listaAnimales.add(animal21);
            listaAnimales.add(animal22);
            listaAnimales.add(animal23);
            listaAnimales.add(animal24);
            listaAnimales.add(animal25);
            listaAnimales.add(animal26);
            listaAnimales.add(animal27);
            listaAnimales.add(animal28);
            listaAnimales.add(animal29);
            listaAnimales.add(animal30);
        } else {
            final ListaPalabras animal1 = new ListaPalabras("PERRO", 1);
            final ListaPalabras animal2 = new ListaPalabras("OSO", 2);
            final ListaPalabras animal3 = new ListaPalabras("SERPIENTE", 3);
            final ListaPalabras animal4 = new ListaPalabras("COCODRILO", 4);
            final ListaPalabras animal5 = new ListaPalabras("PANTERA", 5);
            final ListaPalabras animal6 = new ListaPalabras("BUHO", 6);
            final ListaPalabras animal7 = new ListaPalabras("TORO", 7);
            final ListaPalabras animal8 = new ListaPalabras("GATO", 8);
            final ListaPalabras animal9 = new ListaPalabras("TIGRE", 9);
            final ListaPalabras animal10 = new ListaPalabras("CISNE", 10);
            final ListaPalabras animal11 = new ListaPalabras("PATO", 11);
            final ListaPalabras animal12 = new ListaPalabras("CIERVO", 12);
            final ListaPalabras animal13 = new ListaPalabras("ASNO", 13);
            final ListaPalabras animal14 = new ListaPalabras("BURRO", 14);
            final ListaPalabras animal15 = new ListaPalabras("PALOMA", 15);
            final ListaPalabras animal16 = new ListaPalabras("JIRAFA", 16);
            final ListaPalabras animal17 = new ListaPalabras("GUEPARDO", 17);
            final ListaPalabras animal18 = new ListaPalabras("HIPOPOTAMO", 18);
            final ListaPalabras animal19 = new ListaPalabras("RANA", 19);
            final ListaPalabras animal20 = new ListaPalabras("ELEFANTE", 20);
            final ListaPalabras animal21 = new ListaPalabras("CANGURO", 21);
            final ListaPalabras animal22 = new ListaPalabras("CABALLO", 22);
            final ListaPalabras animal23 = new ListaPalabras("MONO", 23);
            final ListaPalabras animal24 = new ListaPalabras("TORTUGA", 24);
            final ListaPalabras animal25 = new ListaPalabras("CONEJO", 25);
            final ListaPalabras animal26 = new ListaPalabras("CAMELLO", 26);
            final ListaPalabras animal27 = new ListaPalabras("LORO", 27);
            final ListaPalabras animal28 = new ListaPalabras("CAMALEON", 28);
            final ListaPalabras animal29 = new ListaPalabras("FLAMENCO", 29);
            final ListaPalabras animal30 = new ListaPalabras("DELFIN", 30);

            listaAnimales.add(animal1);
            listaAnimales.add(animal2);
            listaAnimales.add(animal3);
            listaAnimales.add(animal4);
            listaAnimales.add(animal5);
            listaAnimales.add(animal6);
            listaAnimales.add(animal7);
            listaAnimales.add(animal8);
            listaAnimales.add(animal9);
            listaAnimales.add(animal10);
            listaAnimales.add(animal11);
            listaAnimales.add(animal12);
            listaAnimales.add(animal13);
            listaAnimales.add(animal14);
            listaAnimales.add(animal15);
            listaAnimales.add(animal16);
            listaAnimales.add(animal17);
            listaAnimales.add(animal18);
            listaAnimales.add(animal19);
            listaAnimales.add(animal20);
            listaAnimales.add(animal21);
            listaAnimales.add(animal22);
            listaAnimales.add(animal23);
            listaAnimales.add(animal24);
            listaAnimales.add(animal25);
            listaAnimales.add(animal26);
            listaAnimales.add(animal27);
            listaAnimales.add(animal28);
            listaAnimales.add(animal29);
            listaAnimales.add(animal30);
        }
        return listaAnimales;
    }

    private static List<ListaPalabras> listaProfesiones() {
        final List<ListaPalabras> listaProfesiones = new ArrayList<>();

        if (Locale.getDefault().getISO3Language().equals("eng")) {
            final ListaPalabras profesion1 = new ListaPalabras("FLORIST", 1);
            final ListaPalabras profesion2 = new ListaPalabras("PROFESSOR", 2);
            final ListaPalabras profesion3 = new ListaPalabras("ARCHITECT", 3);
            final ListaPalabras profesion4 = new ListaPalabras("CARPENTER", 4);
            final ListaPalabras profesion5 = new ListaPalabras("DECORATOR", 5);
            final ListaPalabras profesion6 = new ListaPalabras("POLICEMAN", 6);
            final ListaPalabras profesion7 = new ListaPalabras("WATCHMAKER", 7);
            final ListaPalabras profesion8 = new ListaPalabras("LIFEGUARD", 8);
            final ListaPalabras profesion9 = new ListaPalabras("DIETIST", 9);
            final ListaPalabras profesion10 = new ListaPalabras("GARDENER", 10);
            final ListaPalabras profesion11 = new ListaPalabras("SIGNWRITER", 11);
            final ListaPalabras profesion12 = new ListaPalabras("GEOLOGIST", 12);
            final ListaPalabras profesion13 = new ListaPalabras("JOURNALIST", 13);
            final ListaPalabras profesion14 = new ListaPalabras("FIREMAN", 14);
            final ListaPalabras profesion15 = new ListaPalabras("ECONOMIST", 15);
            final ListaPalabras profesion16 = new ListaPalabras("BIOLOGIST", 16);
            final ListaPalabras profesion17 = new ListaPalabras("FISHERMAN", 17);
            final ListaPalabras profesion18 = new ListaPalabras("JANITOR", 18);
            final ListaPalabras profesion19 = new ListaPalabras("BAKER", 19);
            final ListaPalabras profesion20 = new ListaPalabras("CHEF", 20);
            final ListaPalabras profesion21 = new ListaPalabras("WAITER", 21);
            final ListaPalabras profesion22 = new ListaPalabras("SOMMELIER", 22);
            final ListaPalabras profesion23 = new ListaPalabras("CROUPIER", 23);
            final ListaPalabras profesion24 = new ListaPalabras("PORTER", 24);
            final ListaPalabras profesion25 = new ListaPalabras("PROGRAMMER", 25);
            final ListaPalabras profesion26 = new ListaPalabras("TRANSLATOR", 26);
            final ListaPalabras profesion27 = new ListaPalabras("DESIGNER", 27);
            final ListaPalabras profesion28 = new ListaPalabras("NURSE", 28);
            final ListaPalabras profesion29 = new ListaPalabras("EDITOR", 29);
            final ListaPalabras profesion30 = new ListaPalabras("PRIEST", 30);

            listaProfesiones.add(profesion1);
            listaProfesiones.add(profesion2);
            listaProfesiones.add(profesion3);
            listaProfesiones.add(profesion4);
            listaProfesiones.add(profesion5);
            listaProfesiones.add(profesion6);
            listaProfesiones.add(profesion7);
            listaProfesiones.add(profesion8);
            listaProfesiones.add(profesion9);
            listaProfesiones.add(profesion10);
            listaProfesiones.add(profesion11);
            listaProfesiones.add(profesion12);
            listaProfesiones.add(profesion13);
            listaProfesiones.add(profesion14);
            listaProfesiones.add(profesion15);
            listaProfesiones.add(profesion16);
            listaProfesiones.add(profesion17);
            listaProfesiones.add(profesion18);
            listaProfesiones.add(profesion19);
            listaProfesiones.add(profesion20);
            listaProfesiones.add(profesion21);
            listaProfesiones.add(profesion22);
            listaProfesiones.add(profesion23);
            listaProfesiones.add(profesion24);
            listaProfesiones.add(profesion25);
            listaProfesiones.add(profesion26);
            listaProfesiones.add(profesion27);
            listaProfesiones.add(profesion28);
            listaProfesiones.add(profesion29);
            listaProfesiones.add(profesion30);
        } else {
            final ListaPalabras profesion1 = new ListaPalabras("FLORISTA", 1);
            final ListaPalabras profesion2 = new ListaPalabras("PROFESOR", 2);
            final ListaPalabras profesion3 = new ListaPalabras("ARQUITECTO", 3);
            final ListaPalabras profesion4 = new ListaPalabras("CARPINTERO", 4);
            final ListaPalabras profesion5 = new ListaPalabras("DECORADOR", 5);
            final ListaPalabras profesion6 = new ListaPalabras("POLICIA", 6);
            final ListaPalabras profesion7 = new ListaPalabras("RELOJERO", 7);
            final ListaPalabras profesion8 = new ListaPalabras("SOCORRISTA", 8);
            final ListaPalabras profesion9 = new ListaPalabras("DIETISTA", 9);
            final ListaPalabras profesion10 = new ListaPalabras("JARDINERO", 10);
            final ListaPalabras profesion11 = new ListaPalabras("ROTULISTA", 11);
            final ListaPalabras profesion12 = new ListaPalabras("GEOLOGO", 12);
            final ListaPalabras profesion13 = new ListaPalabras("PERIODISTA", 13);
            final ListaPalabras profesion14 = new ListaPalabras("BOMBERO", 14);
            final ListaPalabras profesion15 = new ListaPalabras("ECONOMISTA", 15);
            final ListaPalabras profesion16 = new ListaPalabras("BIOLOGO", 16);
            final ListaPalabras profesion17 = new ListaPalabras("PESCADOR", 17);
            final ListaPalabras profesion18 = new ListaPalabras("CONSERJE", 18);
            final ListaPalabras profesion19 = new ListaPalabras("PANADERO", 19);
            final ListaPalabras profesion20 = new ListaPalabras("COCINERO", 20);
            final ListaPalabras profesion21 = new ListaPalabras("CAMARERO", 21);
            final ListaPalabras profesion22 = new ListaPalabras("SOMMELIER", 22);
            final ListaPalabras profesion23 = new ListaPalabras("CRUPIER", 23);
            final ListaPalabras profesion24 = new ListaPalabras("PORTERO", 24);
            final ListaPalabras profesion25 = new ListaPalabras("LOGOPEDA", 25);
            final ListaPalabras profesion26 = new ListaPalabras("TRADUCTOR", 26);
            final ListaPalabras profesion27 = new ListaPalabras("TAPICERO", 27);
            final ListaPalabras profesion28 = new ListaPalabras("ARQUEOLOGO", 28);
            final ListaPalabras profesion29 = new ListaPalabras("EDITOR", 29);
            final ListaPalabras profesion30 = new ListaPalabras("SACERDOTE", 30);

            listaProfesiones.add(profesion1);
            listaProfesiones.add(profesion2);
            listaProfesiones.add(profesion3);
            listaProfesiones.add(profesion4);
            listaProfesiones.add(profesion5);
            listaProfesiones.add(profesion6);
            listaProfesiones.add(profesion7);
            listaProfesiones.add(profesion8);
            listaProfesiones.add(profesion9);
            listaProfesiones.add(profesion10);
            listaProfesiones.add(profesion11);
            listaProfesiones.add(profesion12);
            listaProfesiones.add(profesion13);
            listaProfesiones.add(profesion14);
            listaProfesiones.add(profesion15);
            listaProfesiones.add(profesion16);
            listaProfesiones.add(profesion17);
            listaProfesiones.add(profesion18);
            listaProfesiones.add(profesion19);
            listaProfesiones.add(profesion20);
            listaProfesiones.add(profesion21);
            listaProfesiones.add(profesion22);
            listaProfesiones.add(profesion23);
            listaProfesiones.add(profesion24);
            listaProfesiones.add(profesion25);
            listaProfesiones.add(profesion26);
            listaProfesiones.add(profesion27);
            listaProfesiones.add(profesion28);
            listaProfesiones.add(profesion29);
            listaProfesiones.add(profesion30);
        }
        return listaProfesiones;
    }

    private static List<ListaPalabras> listaDeportes() {
        final List<ListaPalabras> listaDeportes = new ArrayList<>();

        if (Locale.getDefault().getISO3Language().equals("eng")) {
            final ListaPalabras deporte1 = new ListaPalabras("FOOTBALL", 1);
            final ListaPalabras deporte2 = new ListaPalabras("BASKETBALL", 2);
            final ListaPalabras deporte3 = new ListaPalabras("HANDBALL", 3);
            final ListaPalabras deporte4 = new ListaPalabras("BOXING", 4);
            final ListaPalabras deporte5 = new ListaPalabras("FENCING", 5);
            final ListaPalabras deporte6 = new ListaPalabras("TENNIS", 6);
            final ListaPalabras deporte7 = new ListaPalabras("RUGBY", 7);
            final ListaPalabras deporte8 = new ListaPalabras("POLE", 8);
            final ListaPalabras deporte9 = new ListaPalabras("HOCKEY", 9);
            final ListaPalabras deporte10 = new ListaPalabras("CRICKET", 10);
            final ListaPalabras deporte11 = new ListaPalabras("GOLF", 11);
            final ListaPalabras deporte12 = new ListaPalabras("CYCLING", 12);
            final ListaPalabras deporte13 = new ListaPalabras("CLIMBING", 13);
            final ListaPalabras deporte14 = new ListaPalabras("HIKING", 14);
            final ListaPalabras deporte15 = new ListaPalabras("DIVING", 15);
            final ListaPalabras deporte16 = new ListaPalabras("SWIMMING", 16);
            final ListaPalabras deporte17 = new ListaPalabras("ROWING", 17);
            final ListaPalabras deporte18 = new ListaPalabras("SURF", 18);
            final ListaPalabras deporte19 = new ListaPalabras("WATERPOLO", 19);
            final ListaPalabras deporte20 = new ListaPalabras("WINDSURF", 20);
            final ListaPalabras deporte21 = new ListaPalabras("TRIAL", 21);
            final ListaPalabras deporte22 = new ListaPalabras("EQUITATION", 22);
            final ListaPalabras deporte23 = new ListaPalabras("JUDO", 23);
            final ListaPalabras deporte24 = new ListaPalabras("KARATE", 24);
            final ListaPalabras deporte25 = new ListaPalabras("CURLING", 25);
            final ListaPalabras deporte26 = new ListaPalabras("SQUASH", 26);
            final ListaPalabras deporte27 = new ListaPalabras("SLACKLINE", 27);
            final ListaPalabras deporte28 = new ListaPalabras("BADMINTON", 28);
            final ListaPalabras deporte29 = new ListaPalabras("VOLLEYBALL", 29);
            final ListaPalabras deporte30 = new ListaPalabras("PADDLE", 30);

            listaDeportes.add(deporte1);
            listaDeportes.add(deporte2);
            listaDeportes.add(deporte3);
            listaDeportes.add(deporte4);
            listaDeportes.add(deporte5);
            listaDeportes.add(deporte6);
            listaDeportes.add(deporte7);
            listaDeportes.add(deporte8);
            listaDeportes.add(deporte9);
            listaDeportes.add(deporte10);
            listaDeportes.add(deporte11);
            listaDeportes.add(deporte12);
            listaDeportes.add(deporte13);
            listaDeportes.add(deporte14);
            listaDeportes.add(deporte15);
            listaDeportes.add(deporte16);
            listaDeportes.add(deporte17);
            listaDeportes.add(deporte18);
            listaDeportes.add(deporte19);
            listaDeportes.add(deporte20);
            listaDeportes.add(deporte21);
            listaDeportes.add(deporte22);
            listaDeportes.add(deporte23);
            listaDeportes.add(deporte24);
            listaDeportes.add(deporte25);
            listaDeportes.add(deporte26);
            listaDeportes.add(deporte27);
            listaDeportes.add(deporte28);
            listaDeportes.add(deporte29);
            listaDeportes.add(deporte30);
        } else {
            final ListaPalabras deporte1 = new ListaPalabras("FUTBOL", 1);
            final ListaPalabras deporte2 = new ListaPalabras("BALONCESTO", 2);
            final ListaPalabras deporte3 = new ListaPalabras("BALONMANO", 3);
            final ListaPalabras deporte4 = new ListaPalabras("BOXEO", 4);
            final ListaPalabras deporte5 = new ListaPalabras("ESGRIMA", 5);
            final ListaPalabras deporte6 = new ListaPalabras("TENIS", 6);
            final ListaPalabras deporte7 = new ListaPalabras("RUGBY", 7);
            final ListaPalabras deporte8 = new ListaPalabras("POLO", 8);
            final ListaPalabras deporte9 = new ListaPalabras("HOCKEY", 9);
            final ListaPalabras deporte10 = new ListaPalabras("CRICKET", 10);
            final ListaPalabras deporte11 = new ListaPalabras("GOLF", 11);
            final ListaPalabras deporte12 = new ListaPalabras("CICLISMO", 12);
            final ListaPalabras deporte13 = new ListaPalabras("ESCALADA", 13);
            final ListaPalabras deporte14 = new ListaPalabras("SENDERISMO", 14);
            final ListaPalabras deporte15 = new ListaPalabras("BUCEO", 15);
            final ListaPalabras deporte16 = new ListaPalabras("NATACION", 16);
            final ListaPalabras deporte17 = new ListaPalabras("REMO", 17);
            final ListaPalabras deporte18 = new ListaPalabras("SURF", 18);
            final ListaPalabras deporte19 = new ListaPalabras("WATERPOLO", 19);
            final ListaPalabras deporte20 = new ListaPalabras("WINDSURF", 20);
            final ListaPalabras deporte21 = new ListaPalabras("TRIAL", 21);
            final ListaPalabras deporte22 = new ListaPalabras("EQUITACION", 22);
            final ListaPalabras deporte23 = new ListaPalabras("JUDO", 23);
            final ListaPalabras deporte24 = new ListaPalabras("KARATE", 24);
            final ListaPalabras deporte25 = new ListaPalabras("CURLING", 25);
            final ListaPalabras deporte26 = new ListaPalabras("SQUASH", 26);
            final ListaPalabras deporte27 = new ListaPalabras("SLACKLINE", 27);
            final ListaPalabras deporte28 = new ListaPalabras("BADMINTON", 28);
            final ListaPalabras deporte29 = new ListaPalabras("VOLEIBOL", 29);
            final ListaPalabras deporte30 = new ListaPalabras("PADEL", 30);

            listaDeportes.add(deporte1);
            listaDeportes.add(deporte2);
            listaDeportes.add(deporte3);
            listaDeportes.add(deporte4);
            listaDeportes.add(deporte5);
            listaDeportes.add(deporte6);
            listaDeportes.add(deporte7);
            listaDeportes.add(deporte8);
            listaDeportes.add(deporte9);
            listaDeportes.add(deporte10);
            listaDeportes.add(deporte11);
            listaDeportes.add(deporte12);
            listaDeportes.add(deporte13);
            listaDeportes.add(deporte14);
            listaDeportes.add(deporte15);
            listaDeportes.add(deporte16);
            listaDeportes.add(deporte17);
            listaDeportes.add(deporte18);
            listaDeportes.add(deporte19);
            listaDeportes.add(deporte20);
            listaDeportes.add(deporte21);
            listaDeportes.add(deporte22);
            listaDeportes.add(deporte23);
            listaDeportes.add(deporte24);
            listaDeportes.add(deporte25);
            listaDeportes.add(deporte26);
            listaDeportes.add(deporte27);
            listaDeportes.add(deporte28);
            listaDeportes.add(deporte29);
            listaDeportes.add(deporte30);
        }

        return listaDeportes;
    }

    private static List<ListaPalabras> listaPeliculas() {
        final List<ListaPalabras> listaPeliculas = new ArrayList<>();

        if (Locale.getDefault().getISO3Language().equals("eng")) {
            final ListaPalabras pelicula1 = new ListaPalabras("CORERED", 1);
            final ListaPalabras pelicula2 = new ListaPalabras("TERMINATOR", 2);
            final ListaPalabras pelicula3 = new ListaPalabras("ALIEN", 3);
            final ListaPalabras pelicula4 = new ListaPalabras("ORIGIN", 4);
            final ListaPalabras pelicula5 = new ListaPalabras("COCO", 5);
            final ListaPalabras pelicula6 = new ListaPalabras("TITANIC", 6);
            final ListaPalabras pelicula7 = new ListaPalabras("BATMAN", 7);
            final ListaPalabras pelicula8 = new ListaPalabras("DUMBO", 8);
            final ListaPalabras pelicula9 = new ListaPalabras("ALADDIN", 9);
            final ListaPalabras pelicula10 = new ListaPalabras("PINOCCHIO", 10);
            final ListaPalabras pelicula11 = new ListaPalabras("BAMBI", 11);
            final ListaPalabras pelicula12 = new ListaPalabras("MULAN", 12);
            final ListaPalabras pelicula13 = new ListaPalabras("TARZAN", 13);
            final ListaPalabras pelicula14 = new ListaPalabras("TANGLED", 14);
            final ListaPalabras pelicula15 = new ListaPalabras("BOLT", 15);
            final ListaPalabras pelicula16 = new ListaPalabras("ENCANTO", 16);
            final ListaPalabras pelicula17 = new ListaPalabras("FROZEN", 17);
            final ListaPalabras pelicula18 = new ListaPalabras("VAIANA", 18);
            final ListaPalabras pelicula19 = new ListaPalabras("SONIC", 19);
            final ListaPalabras pelicula20 = new ListaPalabras("THOR", 20);
            final ListaPalabras pelicula21 = new ListaPalabras("HULK", 21);
            final ListaPalabras pelicula22 = new ListaPalabras("MATRIX", 22);
            final ListaPalabras pelicula23 = new ListaPalabras("UP", 23);
            final ListaPalabras pelicula24 = new ListaPalabras("SEVEN", 24);
            final ListaPalabras pelicula25 = new ListaPalabras("MEMENTO", 25);
            final ListaPalabras pelicula26 = new ListaPalabras("MORBIUS", 26);
            final ListaPalabras pelicula27 = new ListaPalabras("SCREAM", 27);
            final ListaPalabras pelicula28 = new ListaPalabras("UNCHARTED", 28);
            final ListaPalabras pelicula29 = new ListaPalabras("MACBETH", 29);
            final ListaPalabras pelicula30 = new ListaPalabras("RED", 30);

            listaPeliculas.add(pelicula1);
            listaPeliculas.add(pelicula2);
            listaPeliculas.add(pelicula3);
            listaPeliculas.add(pelicula4);
            listaPeliculas.add(pelicula5);
            listaPeliculas.add(pelicula6);
            listaPeliculas.add(pelicula7);
            listaPeliculas.add(pelicula8);
            listaPeliculas.add(pelicula9);
            listaPeliculas.add(pelicula10);
            listaPeliculas.add(pelicula11);
            listaPeliculas.add(pelicula12);
            listaPeliculas.add(pelicula13);
            listaPeliculas.add(pelicula14);
            listaPeliculas.add(pelicula15);
            listaPeliculas.add(pelicula16);
            listaPeliculas.add(pelicula17);
            listaPeliculas.add(pelicula18);
            listaPeliculas.add(pelicula19);
            listaPeliculas.add(pelicula20);
            listaPeliculas.add(pelicula21);
            listaPeliculas.add(pelicula22);
            listaPeliculas.add(pelicula23);
            listaPeliculas.add(pelicula24);
            listaPeliculas.add(pelicula25);
            listaPeliculas.add(pelicula26);
            listaPeliculas.add(pelicula27);
            listaPeliculas.add(pelicula28);
            listaPeliculas.add(pelicula29);
            listaPeliculas.add(pelicula30);
        } else {
            final ListaPalabras pelicula1 = new ListaPalabras("ACORRALADO", 1);
            final ListaPalabras pelicula2 = new ListaPalabras("TERMINATOR", 2);
            final ListaPalabras pelicula3 = new ListaPalabras("ALIEN", 3);
            final ListaPalabras pelicula4 = new ListaPalabras("ORIGEN", 4);
            final ListaPalabras pelicula5 = new ListaPalabras("COCO", 5);
            final ListaPalabras pelicula6 = new ListaPalabras("TITANIC", 6);
            final ListaPalabras pelicula7 = new ListaPalabras("BATMAN", 7);
            final ListaPalabras pelicula8 = new ListaPalabras("DUMBO", 8);
            final ListaPalabras pelicula9 = new ListaPalabras("ALADDIN", 9);
            final ListaPalabras pelicula10 = new ListaPalabras("PINOCHO", 10);
            final ListaPalabras pelicula11 = new ListaPalabras("BAMBI", 11);
            final ListaPalabras pelicula12 = new ListaPalabras("MULAN", 12);
            final ListaPalabras pelicula13 = new ListaPalabras("TARZAN", 13);
            final ListaPalabras pelicula14 = new ListaPalabras("ENREDADOS", 14);
            final ListaPalabras pelicula15 = new ListaPalabras("BOLT", 15);
            final ListaPalabras pelicula16 = new ListaPalabras("ENCANTO", 16);
            final ListaPalabras pelicula17 = new ListaPalabras("FROZEN", 17);
            final ListaPalabras pelicula18 = new ListaPalabras("VAIANA", 18);
            final ListaPalabras pelicula19 = new ListaPalabras("SONIC", 19);
            final ListaPalabras pelicula20 = new ListaPalabras("THOR", 20);
            final ListaPalabras pelicula21 = new ListaPalabras("HULK", 21);
            final ListaPalabras pelicula22 = new ListaPalabras("MATRIX", 22);
            final ListaPalabras pelicula23 = new ListaPalabras("UP", 23);
            final ListaPalabras pelicula24 = new ListaPalabras("SEVEN", 24);
            final ListaPalabras pelicula25 = new ListaPalabras("MEMENTO", 25);
            final ListaPalabras pelicula26 = new ListaPalabras("MORBIUS", 26);
            final ListaPalabras pelicula27 = new ListaPalabras("SCREAM", 27);
            final ListaPalabras pelicula28 = new ListaPalabras("UNCHARTED", 28);
            final ListaPalabras pelicula29 = new ListaPalabras("MACBETH", 29);
            final ListaPalabras pelicula30 = new ListaPalabras("RED", 30);

            listaPeliculas.add(pelicula1);
            listaPeliculas.add(pelicula2);
            listaPeliculas.add(pelicula3);
            listaPeliculas.add(pelicula4);
            listaPeliculas.add(pelicula5);
            listaPeliculas.add(pelicula6);
            listaPeliculas.add(pelicula7);
            listaPeliculas.add(pelicula8);
            listaPeliculas.add(pelicula9);
            listaPeliculas.add(pelicula10);
            listaPeliculas.add(pelicula11);
            listaPeliculas.add(pelicula12);
            listaPeliculas.add(pelicula13);
            listaPeliculas.add(pelicula14);
            listaPeliculas.add(pelicula15);
            listaPeliculas.add(pelicula16);
            listaPeliculas.add(pelicula17);
            listaPeliculas.add(pelicula18);
            listaPeliculas.add(pelicula19);
            listaPeliculas.add(pelicula20);
            listaPeliculas.add(pelicula21);
            listaPeliculas.add(pelicula22);
            listaPeliculas.add(pelicula23);
            listaPeliculas.add(pelicula24);
            listaPeliculas.add(pelicula25);
            listaPeliculas.add(pelicula26);
            listaPeliculas.add(pelicula27);
            listaPeliculas.add(pelicula28);
            listaPeliculas.add(pelicula29);
            listaPeliculas.add(pelicula30);
        }
        return listaPeliculas;
    }

    public static List<ListaPalabras> getPalabras(String temaElegido) {
        switch (temaElegido) {
            case "capitales":
                return listaCapitales();
            case "comida":
                return listaComidas();
            case "animales":
                return listaAnimales();
            case "profesiones":
                return listaProfesiones();
            case "deportes":
                return listaDeportes();
            case "cine":
                return listaPeliculas();
            default:
                return listaPeliculas();
        }
    }
}
